### ISSUE TITLE
Badge sort: Aus 2013 < Dev/Prime 2013

### ISSUE THREAD

**Issue by mddburgess** [gespo89/PAXSignatureGenerator#4]
PAX Aus 2013 was held in July between East and Dev/Prime, so the badge should appear between those two in the sorted order.

**Comment by gespo89** [comment]
Agreed, I was thinking about this, and am torn between adding an exception for that one year in the sort, or adding dates for the PAX. The latter is cleaner, but will require constant updating each year, so I'll probably roll with the former for now.

**Comment by mddburgess** [comment]
That was my thinking as well. Unless they significantly change when they hold each PAX in the future, adding a special case for 2013 will be sufficient.
